apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: rekrutteringstreff-api
  namespace: toi
  labels:
    team: toi
spec:
  image: {{ image }}
  port: 8080
  ingresses:
  {{#each ingress as |url|}}
    - {{url}}
  {{/each}}
  liveness:
    path: /isalive
  readiness:
    path: /isready
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    min: {{ min_replicas }}
    max: {{ max_replicas }}
  secureLogs:
    enabled: true
  resources:
    limits:
      cpu: 3000m
      memory: 2048Mi
    requests:
      cpu: 100m
      memory: 512Mi
  accessPolicy:
    inbound:
      rules:
        - application: rekrutteringsbistand-frontend
        - application: rekrutteringstreff-minside-api
    outbound:
      rules:
        - application: rekrutteringsbistand-kandidatsok-api
      external:
        - host: fakedings.intern.dev.nav.no
        - host: {{ openai_azure_host }}
          ports:
            - port: 443
  tokenx:
    enabled: true
  azure:
    application:
      enabled: true
      allowAllUsers: false
      claims:
        extra:
          - NAVident
        groups:
          - id: {{ adGruppeUtvikler }}
  kafka:
    pool: {{ kafka_pool }}
  gcp:
    sqlInstances:
      - type: {{ postgres }}
        databases:
          - name: rekrutteringstreff-db
        tier: {{ gcp_db_tier }}
        diskAutoresize: {{ gcp_disk_autoresize }}
        cascadingDelete: true
  envFrom:
    - secret: openai-toi-rekrutteringsbistand-stilling
  env:
    - name: REKRUTTERINGSBISTAND_ARBEIDSGIVERRETTET
      value: {{adGruppeArbeidsgiverrettet}}
    - name: REKRUTTERINGSBISTAND_UTVIKLER
      value: {{adGruppeUtvikler}}
    - name: KANDIDATSOK_API_URL
      value: {{kandidatsok_api_url}}
    - name: KANDIDATSOK_API_SCOPE
      value: {{kandidatsok_api_scope}}
  observability:
    logging:
      destinations:
        - id: loki
        - id: elastic
      enabled: true