apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: rekrutteringstreff-api
  namespace: toi
  labels:
    team: toi
spec:
  image: {{ image }}
  port: 8301
  ingresses:
    - {{ ingress }}
  liveness:
    path: /isalive
  readiness:
    path: /isready
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    min: {{ min_replicas }}
    max: {{ max_replicas }}
  secureLogs:
    enabled: true
  resources:
    limits:
      cpu: 3000m
      memory: 2048Mi
    requests:
      cpu: 100m
      memory: 512Mi
  accessPolicy:
    inbound:
      rules:
        - application: rekrutteringsbistand
          namespace: toi
          cluster: { { cluster } }
  azure:
    application:
      enabled: true
      allowAllUsers: false
  kafka:
    pool: {{ kafka_pool }}
  gcp:
    sqlInstances:
      - type: POSTGRES_15
        databases:
          - name: rekrutteringstreff-db
        tier: {{ gcp_db_tier }}
        diskAutoresize: {{ gcp_disk_autoresize }}
