apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: rekrutteringstreff-api
  namespace: toi
  labels:
    team: toi
spec:
  image: {{ image }}
  port: 8080
  ingresses:
  {{#each ingress as |url|}}
    - {{url}}
  {{/each}}
  liveness:
    path: /isalive
    port: 8080
  readiness:
    path: /isready
    port: 8080
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    min: {{ min_replicas }}
    max: {{ max_replicas }}
  secureLogs:
    enabled: true
  resources:
    limits:
      cpu: 3000m
      memory: 2048Mi
    requests:
      cpu: 100m
      memory: 512Mi
  accessPolicy:
    inbound:
      rules:
        - application: rekrutteringsbistand-frontend
        - application: rekrutteringstreff-minside-api
    outbound:
      rules:
        - application: rekrutteringsbistand-kandidatsok-api
        - application: modiacontextholder
          namespace: personoversikt
      external:
        - host: fakedings.intern.dev.nav.no
        - host: {{ openai_azure_host }}
          ports:
            - port: 443
  tokenx:
    enabled: true
  azure:
    application:
      enabled: true
      allowAllUsers: false
      claims:
        extra:
          - NAVident
        groups:
          - id: {{ adGruppeUtvikler }}
          - id: {{ adGruppeArbeidsgiverrettet }}
          - id: {{ adGruppeJobbsokerrettet }}
  kafka:
    pool: {{ kafka_pool }}
  gcp:
    sqlInstances:
      - type: {{ postgres }}
        databases:
          - name: rekrutteringstreff-api
        tier: {{ gcp_db_tier }}
        diskAutoresize: {{ gcp_disk_autoresize }}
  envFrom:
    - secret: openai-toi-rekrutteringstreff
  env:
    - name: REKRUTTERINGSBISTAND_ARBEIDSGIVERRETTET
      value: {{adGruppeArbeidsgiverrettet}}
    - name: REKRUTTERINGSBISTAND_UTVIKLER
      value: {{adGruppeUtvikler}}
    - name: REKRUTTERINGSBISTAND_JOBBSOKERRETTET
      value: {{adGruppeJobbsokerrettet}}
    - name: KANDIDATSOK_API_URL
      value: {{kandidatsok_api_url}}
    - name: KANDIDATSOK_API_SCOPE
      value: {{kandidatsok_api_scope}}
    - name: MODIACONTEXTHOLDER_URL
      value: {{modiacontextholder_url}}
    - name: MODIACONTEXTHOLDER_SCOPE
      value: {{modiacontextholder_scope}}
    - name: KAFKA_RAPID_TOPIC
      value: toi.rapid-1
    - name: KAFKA_CONSUMER_GROUP_ID
      value: {{kafka_consumer_group_id}}
    - name: PILOTKONTORER
      value: {{pilotkontorer}}
    - name: OPENAI_API_URL
      value: "https://{{openai_azure_host}}/openai/deployments/{{openai_deployment}}/chat/completions?api-version={{openai_api_version}}"
    - name: OPENAI_DEPLOYMENT
      value: {{openai_deployment}}
  observability:
    logging:
      destinations:
        - id: loki
        - id: elastic
      enabled: true