kafka_pool: nav-prod
"ingress": ["https://rekrutteringstreff-api.intern.nav.no/api"]
cluster: prod-gcp
min_replicas: 2
max_replicas: 4
gcp_db_tier: db-custom-1-3840
gcp_disk_autoresize: true
postgres: POSTGRES_17
openai_azure_host: "todo"
openai_deployment: "toi-gpt-4.1"
openai_api_version: "2025-01-01-preview"
adGruppeArbeidsgiverrettet: "46c8e3b2-0469-4740-983f-d8cd2b6e4fee"
adGruppeUtvikler: "41080368-439f-4128-858a-afbef876431e"
adGruppeJobbsokerrettet: "66b70a6a-3d05-47b3-8b5a-47c681dcd1d5"
modiacontextholder_url: "http://modiacontextholder.personoversikt"
modiacontextholder_scope: "api://prod-gcp.personoversikt.modiacontextholder/.default"
pilotkontorer: ""
