package no.nav.toi

enum class JobbsøkerHendelsestype {
    OPPRETTET,
    OPPDATERT,
    SLETTET,
    INVITERT,
    SVAR_FJERNET_AV_EIER,
    SVART_JA_TIL_INVITASJON,
    SVART_JA_TIL_INVITASJON_AV_EIER,
    SVART_NEI_TIL_INVITASJON,
    SVART_NEI_TIL_INVITASJON_AV_EIER,
    AKTIVITETSKORT_OPPRETTELSE_FEIL,
    SVART_JA_TREFF_AVLYST,
    SVART_JA_TREFF_FULLFØRT,
    IKKE_SVART_TREFF_AVLYST,
    IKKE_SVART_TREFF_FULLFØRT,
    TREFF_ENDRET_ETTER_PUBLISERING,
    TREFF_ENDRET_ETTER_PUBLISERING_NOTIFIKASJON,
    MOTTATT_SVAR_FRA_MINSIDE,
    FÅTT_JOBB,
    ANGRE_FÅTT_JOBB,
    REGISTRERT_OPPMØTE,
    REGISTRERT_OPPMØTE_FJERNET,
    PLASSERT_I_ROM,
    INTERESSE_REGISTRERT,
    ANGRE_INTERESSE_REGISTRERT,
    SATT_OPP_TIL_INTERVJU,
    ANGRE_SATT_OPP_TIL_INTERVJU,
    VURDERT,
    NOTAT_LAGT_TIL,
    NOTAT_FJERNET,
    ANDREGANGSINTERVJU_AVTALT,
    ANGRE_ANDREGANGSINTERVJU_AVTALT,
    JOBBTILBUD_GITT,
    ANGRE_JOBBTILBUD_GITT,
}

enum class ArbeidsgiverHendelsestype {
    OPPRETTET, OPPDATERT, SLETTET, REAKTIVERT, BEHOV_ENDRET,
    INTERESSE_REGISTRERT,
    ANGRE_INTERESSE_REGISTRERT,
    SATT_OPP_TIL_INTERVJU,
    ANGRE_SATT_OPP_TIL_INTERVJU,
    VURDERT,
    NOTAT_LAGT_TIL,
    NOTAT_FJERNET,
    ANDREGANGSINTERVJU_AVTALT,
    ANGRE_ANDREGANGSINTERVJU_AVTALT,
    JOBBTILBUD_GITT,
    ANGRE_JOBBTILBUD_GITT,
    ROTASJON_TILDELT,
}

enum class FormidlingHendelsestype {
    OPPRETTET, SLETTET
}

enum class RekrutteringstreffHendelsestype {
    OPPRETTET, OPPDATERT, SLETTET, PUBLISERT, GJENÅPNET, FULLFØRT, AVLYST, AVPUBLISERT, TREFF_ENDRET_ETTER_PUBLISERING, EIER_LAGT_TIL, EIER_FJERNET, KONTOR_LAGT_TIL,
    TREFFGJENNOMFORING_OPPRETTET,
    TREFFGJENNOMFORING_OPPSETT_ENDRET,
    TREFFGJENNOMFORING_ROMFORDELING_ENDRET,
    TREFFGJENNOMFORING_INTERVJUFORDELING_FORDELT,
}

enum class AktørType { ARRANGØR, JOBBSØKER, ARBEIDSGIVER, SYSTEM, MARKEDSKONTAKT_ELLER_VEILEDER}
