package no.nav.toi


enum class JobbsøkerHendelsestype {
    OPPRETTET, OPPDATERT, SLETTET, INVITERT, MØTT_OPP, IKKE_MØTT_OPP, SVART_JA_TIL_INVITASJON, SVART_NEI_TIL_INVITASJON, AKTIVITETSKORT_OPPRETTELSE_FEIL
}

enum class ArbeidsgiverHendelsestype {
    OPPRETTET, OPPDATERT, SLETTET
}

enum class RekrutteringstreffHendelsestype {
    OPPRETTET, OPPDATERT, SLETTET, PUBLISERT, GJENÅPNET, FULLFØRT, AVLYST, AVPUBLISERT
}

enum class AktørType { ARRANGØR, JOBBSØKER, ARBEIDSGIVER }