package no.nav.toi


enum class JobbsøkerHendelsestype {
    OPPRETTET, OPPDATERT, SLETTET, INVITERT, SVART_JA_TIL_INVITASJON, SVART_NEI_TIL_INVITASJON, AKTIVITETSKORT_OPPRETTELSE_FEIL, SVART_JA_TREFF_AVLYST, SVART_JA_TREFF_FULLFØRT, IKKE_SVART_TREFF_AVLYST, IKKE_SVART_TREFF_FULLFØRT, TREFF_ENDRET_ETTER_PUBLISERING, TREFF_ENDRET_ETTER_PUBLISERING_NOTIFIKASJON, MOTTATT_SVAR_FRA_MINSIDE;

    fun erSvarPåInvitasjon(): Boolean =
        this == SVART_JA_TIL_INVITASJON || this == SVART_NEI_TIL_INVITASJON
}

enum class ArbeidsgiverHendelsestype {
    OPPRETTET, OPPDATERT, SLETTET
}

enum class RekrutteringstreffHendelsestype {
    OPPRETTET, OPPDATERT, SLETTET, PUBLISERT, GJENÅPNET, FULLFØRT, AVLYST, AVPUBLISERT, TREFF_ENDRET_ETTER_PUBLISERING
}

enum class AktørType { ARRANGØR, JOBBSØKER, ARBEIDSGIVER, SYSTEM }