apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: rekrutteringstreff-minside-api
  namespace: toi
  labels:
    team: toi
spec:
  image: {{ image }}
  port: 8080
  ingresses:
  {{#each ingress as |url|}}
    - {{url}}
  {{/each}}
  liveness:
    path: /isalive
  readiness:
    path: /isready
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    min: {{ min_replicas }}
    max: {{ max_replicas }}
  secureLogs:
    enabled: true
  resources:
    limits:
      cpu: 3000m
      memory: 2048Mi
    requests:
      cpu: 100m
      memory: 512Mi
  accessPolicy:
    inbound:
      rules:
        - application: rekrutteringstreff-bruker
  tokenx:
    enabled: true
  azure:
    application:
      enabled: true
      allowAllUsers: false
  env:
    - name: REKRUTTERINGSBISTAND_ARBEIDSGIVERRETTET
      value: {{adGruppeArbeidsgiverrettet}}
    - name: REKRUTTERINGSBISTAND_UTVIKLER
      value: {{adGruppeUtvikler}}
    - name: REKRUTTERINGSTREFF_SCOPE
      value: {{ rekrutteringstreff_scope }}
  observability:
    logging:
      destinations:
        - id: loki
        - id: elastic
      enabled: true
