kafka_pool: nav-prod
"ingress": [
  "https://rekrutteringstreff-minside-api.nav.no/api"
]
cluster: prod-gcp
min_replicas: 2
max_replicas: 4
rekrutteringstreff_audience: prod-gpc.toi.rekrutteringstreff-api
