kafka_pool: nav-prod
"ingress": [
  "https://rekrutteringstreff-minside-api.nav.no/api",
  "https://rekrutteringstreff-minside-api.nav.no/isalive",
  "https://rekrutteringstreff-minside-api.nav.no/isready",
]
cluster: prod-gcp
min_replicas: 2
max_replicas: 4
rekrutteringstreff_audience: prod-gcp:toi:rekrutteringstreff-api
