package no.nav.toi.arbeidsgiver

object Arbeidssprak {
    val verdier: List<String> = listOf(
        "Abaluhyisk",
        "Afar/Danakil",
        "Afrikaans",
        "Ainu",
        "Akan/Twi-Fante",
        "Albansk",
        "Aleutisk",
        "Aluf",
        "Amharisk",
        "Amoi",
        "Arabisk",
        "Arameisk",
        "Armensk",
        "Assamesisk",
        "Aymara",
        "Azerisk/Azerbajansk",
        "Badini (Sør-Øst-Kurdisk)",
        "Baluchisk",
        "Bambara",
        "Bandi",
        "Bantu",
        "Basjkirsk",
        "Baskisk",
        "Bemba/Kibemba",
        "Bengalsk",
        "Berber",
        "Bichelamar/Bislama",
        "Biharisk",
        "Blindeskrift",
        "Bokmål",
        "Bono",
        "Bosnisk",
        "Bulgarsk",
        "Burmesisk",
        "Bushman",
        "Cebuano",
        "Chichewa",
        "Chishona/Korekore",
        "Cotokali",
        "Dagbani",
        "Dansk",
        "Darisk/Persisk",
        "Dendisk/Dendi (Benin)",
        "Dendisk/Dendi (Den sentralafrikanske republikk)",
        "Dinka",
        "Divehi/Maldivisk",
        "Dogon (Toro So Dogon",
        "Dyula/Dioula",
        "Dzongka/Bhutanisk",
        "Efik-Ibibio",
        "Engelsk",
        "Eskimo-Aleut",
        "Estisk",
        "Ewe",
        "Fang (Ekvatorial-Guinea)",
        "Fang (Kamerun)",
        "Fante",
        "Fejli (Kurdisk)",
        "Fidjiansk",
        "Filipino/Tagalog",
        "Finsk",
        "Flamsk",
        "Fon",
        "Fransk",
        "Fransk Patois",
        "Frisisk",
        "Fukien",
        "Ful/Fula/Fulfulde",
        "Fulbe",
        "Færøyisk",
        "Ga/Gan",
        "Gah (Se GA)",
        "Galisisk",
        "Georgisk/Gruzinsk",
        "Gresk",
        "Grønlandsk",
        "Guarani",
        "Gujarati",
        "Gælisk (Irsk)",
        "Gælisk (Skotsk)",
        "Haitisk",
        "Hakka/Kejia",
        "Hassania/Zenaga",
        "Hausa",
        "Hebraisk",
        "Herero",
        "Hindi",
        "Hviterussisk",
        "Ibo/Igbo",
        "Ikiribati/Gilbertes",
        "Indonesisk",
        "Irsk",
        "Islandsk",
        "Italiensk",
        "Japansk",
        "Javanesisk",
        "Jiddisch",
        "Kabre",
        "Kabylisk",
        "Kamba/Kikamba",
        "Kampa",
        "Kanaresisk/Kannada",
        "Kantonesisk/Yue",
        "Kanuri",
        "Karen",
        "Kaschmirsk",
        "Katalansk",
        "Kavango",
        "Kazakisk",
        "Khmer/Kambodsjansk",
        "Kinesisk",
        "Kinyarwanda",
        "Kirgisisk",
        "Kirundi/Ikirundi",
        "Kongo/Kikongo",
        "Konkani/Goanesisk",
        "Koreansk",
        "Korsikansk",
        "Kreol",
        "Kreolsk",
        "Krio",
        "Kroatisk",
        "Kru",
        "Kurdisk",
        "Kurmanji (Nord-Kurdisk)",
        "Kuyu/Kikuyu/Gikuyu",
        "Kymrisk",
        "Laotisk",
        "Latin",
        "Latvisk",
        "Limba",
        "Lingala",
        "Litauisk",
        "Lozi",
        "Luba/Kiluba",
        "Luganda/Ganda",
        "Luhya/Luyia/Luluhya",
        "Lulesamisk",
        "Lunda",
        "Luo",
        "Lutoro",
        "Luvale",
        "Luxemburgisk",
        "Maduresisk",
        "Makedonsk",
        "Makua-Lomwe/Imakua",
        "Malagassisk",
        "Malayalam",
        "Malayisk",
        "Malinke",
        "Maltesisk",
        "Mandarin",
        "Mande/Mandi",
        "Mandinka/Maninka/Mandingo",
        "Mandsjurisk",
        "Manx",
        "Maori",
        "Marathi",
        "Marisk",
        "Marwarisk",
        "Masai",
        "Maya",
        "Mende",
        "Mina",
        "Moldavisk",
        "Mongolsk",
        "Mordvinsk",
        "More",
        "Mozabitisk/Mzabi",
        "Nama",
        "Nandi/Nandikipsigis",
        "Nauhatl/Aztekisk",
        "Nauru/Nauruansk",
        "Navajo/Navaho",
        "Ndebele",
        "Nederlandsk",
        "Nepali/Gurkhal",
        "Nizma",
        "Nordsamisk",
        "Norsk",
        "Norsk tegnspråk",
        "Nyamwezi/Kinyamwezi",
        "Nyanja/Chewa/Kichew",
        "Nynorsk",
        "Occitansk",
        "Oriya",
        "Oromisk",
        "Otetele",
        "Ovambo/Kwanyama",
        "Pasjto",
        "Patani",
        "Persisk/Farsi",
        "Polsk",
        "Portugisisk",
        "Portugisisk (Brasil)",
        "Punjabi",
        "Quechua",
        "Quiché",
        "Retoromansk",
        "Romani/Romanes",
        "Rumensk",
        "Runyakitara",
        "Rusinsk",
        "Russisk",
        "Samisk",
        "Samoansk",
        "Sango",
        "Sanskrit",
        "Santali",
        "Sarakolle/Soninke",
        "Sardisk/Sardinsk",
        "Senufo",
        "Serbisk",
        "Serbokroatisk",
        "Sesotho/Sesuto/Soth",
        "Setswana/Tswana",
        "Shawi/Shawe",
        "Shawiya",
        "Shona",
        "Sindebele",
        "Sindhi",
        "Singalesisk/Sinhala",
        "Siswati",
        "Sjilkisk/Sjluh",
        "Skotsk",
        "Slovakisk",
        "Slovensk",
        "Somalisk",
        "Songhai-Djerma",
        "Sorani (Sentral-Kurdisk)",
        "Sorbisk",
        "Spansk",
        "Sranan/Taki-Taki",
        "Susu",
        "Svensk",
        "Swahili",
        "Swazi/Isiswazi/Swat",
        "Syrisk/Assyrisk",
        "Sør-Kurdisk",
        "Sørsamisk",
        "Tadzjikisk",
        "Tahitisk",
        "Tamashak/Tuareg",
        "Tamezighi/Tamazight",
        "Tamil/Tamilsk",
        "Tasjilhait/Chlech",
        "Tatarisk",
        "Tegnspråk",
        "Telugu",
        "Temne",
        "Teochew/Teochiu",
        "Thailandsk",
        "Tibetansk",
        "Tigre",
        "Tigrinja/Tigrinsk",
        "Tjerkessisk/Kabardi",
        "Tjuvasjisk",
        "Tok Pisin",
        "Tonga/Tongansk",
        "Tshiluba",
        "Tsjekkisk",
        "Tsjetsjensk",
        "Turabdinsk",
        "Turkana/Teso-Turkan",
        "Turkmensk",
        "Twi",
        "Tyrkisk",
        "Tysk",
        "Uigurisk",
        "Ukrainsk",
        "Umbundu/Ovimbundu",
        "Ungarsk",
        "Urdu",
        "Urmisk",
        "Uzbekisk",
        "Vietnamesisk",
        "Walisisk",
        "Wollof",
        "Xhosa/Isixhosa",
        "Yi/Lolo",
        "Yoruba",
        "Yupik",
        "Zande/Azande",
        "Zhuang",
        "Zulu",
    )

    private val gyldigeVerdier = verdier.toSet()
    private const val annet = "Annet"

    // TODO: KAn fjernes nr gamle treff er ryddet bort
    private val gamleEnumVerdier = mapOf(
        "NORSK" to "Norsk",
        "ENGELSK" to "Engelsk",
        "SVENSK" to "Svensk",
        "DANSK" to "Dansk",
        "TYSK" to "Tysk",
        "FRANSK" to "Fransk",
        "SPANSK" to "Spansk",
        "ANNET" to null,
    )

    fun fraApiNavn(apiNavn: String): String =
        if (apiNavn in gyldigeVerdier) apiNavn else throw IllegalArgumentException("Ukjent arbeidsspråk [$apiNavn].")

    fun validerOgFiltrer(arbeidssprak: List<String>): List<String> =
        arbeidssprak.filterNot { it == annet }.map(::fraApiNavn)

    fun fraLagretVerdi(verdi: String): String? =
        gamleEnumVerdier.getOrElse(verdi) { if (verdi in gyldigeVerdier) verdi else null }
}