on:
  workflow_call:
    inputs:
      app_name:
        required: true
        type: string
      deploy_dev_branch:
        required: false
        type: string

permissions:
  contents: read
  id-token: write

jobs:
  build-and-publish:
    name: Build, test, and publish
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Java v21.x
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21.x'
      - name: Gradle test and build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          chmod +x ./gradlew
          ./gradlew :apps:${{ inputs.app_name }}:test :apps:${{ inputs.app_name }}:build
      - name: Push docker image to GAR
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: toi
          image_suffix: ${{ inputs.app_name }}
          dockerfile: apps/${{ inputs.app_name }}/Dockerfile
          docker_context: apps/${{ inputs.app_name }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          tag: ${{ github.ref == 'refs/heads/main' && 'latest' || github.sha }}
          build_args: |
            APP_NAME=${{ inputs.app_name }}

  deploy-to-dev-gcp:
    name: Deploy to dev-gcp
    needs: build-and-publish
    if: github.ref == 'refs/heads/main' || github.ref == inputs.deploy_dev_branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: apps/${{ inputs.app_name }}/.nais/app.yaml
          VARS: apps/${{ inputs.app_name }}/.nais/dev-gcp.yaml
          VAR: image=${{ needs.build-and-publish.outputs.image }}

 # deploy-to-prod-gcp:
 #   name: Deploy to prod-gcp
 #   needs: [ build-and-publish, deploy-to-dev-gcp ]
 #   if: github.ref == 'refs/heads/main'
 #   runs-on: ubuntu-latest
 #   steps:
 #     - uses: actions/checkout@v4
 #     - uses: nais/deploy/actions/deploy@v2
 #       env:
 #         CLUSTER: prod-gcp
 #         RESOURCE: apps/${{ inputs.app_name }}/.nais/app.yaml,apps/${{ inputs.app_name }}/.nais/alerts.yaml
 #         VARS: apps/${{ inputs.app_name }}/.nais/prod-gcp.yaml
 #         VAR: image=${{ needs.build-and-publish.outputs.image }}

  call-trivy-security-scan:
    needs: build-and-publish
    uses: navikt/toi-github-actions-workflows/.github/workflows/trivy-security-scan.yaml@main
    with:
      image: ${{ needs.build-and-publish.outputs.image }}
    permissions:
      id-token: write
      security-events: write
    secrets: inherit
