name: 'Oppdater Docker baseimage: rekrutteringstreff-api'
on:
  schedule:
    - cron: '10 6 * * 1'
  workflow_dispatch:
jobs:
  call-oppdater-docker-baseimage:
    uses: navikt/toi-github-actions-workflows/.github/workflows/oppdater-docker-baseimage.yaml@v16
    with:
      app-navn: rekrutteringstreff-api
      deploy-workflow-filnavn: deploy-rekrutteringstreff-api.yaml
    permissions:
      id-token: write
      actions: write
